# src1/config.yaml
seed: 42

dataset:
  name: ravdess_split
  root: "/home/agrilab/Documentos/Cassanova/Fer-video/data"  # <–– aqui!
  max_frames: 12
  frames_per_second: 1

model:
  name: lstm
  input_size: 512
  hidden_size: 256
  num_layers: 2
  dropout: 0.3
  cnn_backbone: resnet18
  freeze_cnn: true

training:
  batch_size: 8
  num_epochs: 50
  lr: 1e-4
  weight_decay: 1e-4
  num_workers: 4
  precision: 16
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  val_check_interval: 1
  log_interval: 10
  checkpoint_dir: "checkpoints/"
  log_dir: "logs/"
  early_stopping:
    enable: true
    patience: 10
