
# Config for ResNet18 on CAER
name: "frame_resnet50_caer"
seed: 42

dataset:
  name: "CAER"
  root: "F:/Git/fer-video/fer-video/data"
  max_frames: 3
  frames_per_second: 1
  class_mappings:
    caer:       ['Anger','Disgust','Fear','Happy','Neutral','Sad','Surprise']

model:
  model_type: frame
  name: frame_classifier
  cnn_backbone: "resnet50"
  pretrained: true
  freeze_backbone: false
  dropout: 0.4

training:
  batch_size: 32  # Aumentar para GPU
  num_epochs: 1
  lr: 1e-4
  weight_decay: 1e-4
  num_workers: 4  # Aumentar para GPU
  precision: "16-mixed"  # Mixed precision para GPU
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1  # Reduzir já que batch_size maior
  val_check_interval: 1
  log_interval: 10
  checkpoint_dir: "checkpoints/"
  log_dir: "logs/"
  early_stopping:
    enable: true
    patience: 10

wandb:
  enable: true
  entity: "snaxofc10-utfpr-medianeira"
  project: "fer_video"
