
# Config for YOLOv8-Large-Cls on CAER
name: "frame_yolov8l_cls_caer"
seed: 42

dataset:
  name: "caer"
  root: "/home/agrilab/Documentos/Cassanova/Fer-video/data"
  max_frames: 3
  frames_per_second: 1
  class_mappings:
    caer:       ['Anger','Disgust','Fear','Happy','Neutral','Sad','Surprise']

model:
  model_type: frame
  name: frame_classifier
  cnn_backbone: "yolov8l_cls"
  pretrained: true
  freeze_backbone: false
  dropout: 0.5

training:
  batch_size: 8
  num_epochs: 1
  lr: 1e-5
  weight_decay: 1e-4
  num_workers: 4
  precision: 16
  gradient_clip_val: 1.0
  accumulate_grad_batches: 4
  val_check_interval: 1
  log_interval: 10
  checkpoint_dir: "checkpoints/"
  log_dir: "logs/"
  early_stopping:
    enable: true
    patience: 10

wandb:
  enable: true
  entity: "snaxofc10-utfpr-medianeira"
  project: "fer_video"
