
# Override parameters for frame-based experiment with a more powerful ViT
name: "vitv2_powerful"
seed: 42

dataset:
  name: ravdess_split
  root: "/home/agrilab/Documentos/Cassanova/Fer-video/data"
  max_frames: 12
  frames_per_second: 1
  class_mappings:
    caer:       ['Anger','Disgust','Fear','Happy','Neutral','Sad','Surprise']
    cmu_moisei: ['angry','disgust','fear','happy','neutral','sad','surprised']
    ravdess:    ['angry','calm','disgust','fear','happy','neutral','sad','surprised']

model:
  model_type: frame
  name: frame_classifier
  cnn_backbone: "eva02_base_patch14_224.mim_in22k" # Using a more powerful ViT model
  pretrained: true
  freeze_backbone: false # Start with fine-tuning the backbone

training:
  batch_size: 2
  num_epochs: 30
  lr: 1e-5 # Lower learning rate for fine-tuning
  weight_decay: 1e-4
  num_workers: 4
  precision: 16
  gradient_clip_val: 1.0
  accumulate_grad_batches: 4
  val_check_interval: 1
  log_interval: 10
  checkpoint_dir: "checkpoints/"
  log_dir: "logs/"
  early_stopping:
    enable: true
    patience: 10

wandb:
  enable: true
  entity: "snaxofc10-utfpr-medianeira"
  project: "fer_video"
